# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simMergeWindow.ui'
#
# Created: Tue Oct 11 22:50:00 2022
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MergeWin(object):
    def setupUi(self, MergeWin):
        MergeWin.setObjectName("MergeWin")
        MergeWin.resize(1220, 725)
        self.verticalLayout = QtWidgets.QVBoxLayout(MergeWin)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameTop = QtWidgets.QFrame(MergeWin)
        self.frameTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTop.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameTop.setObjectName("frameTop")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameTop)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.QpbRefresh = QtWidgets.QPushButton(self.frameTop)
        self.QpbRefresh.setMinimumSize(QtCore.QSize(75, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbRefresh.setFont(font)
        self.QpbRefresh.setObjectName("QpbRefresh")
        self.horizontalLayout.addWidget(self.QpbRefresh)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frameTop)
        self.frameMed = QtWidgets.QFrame(MergeWin)
        self.frameMed.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMed.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameMed.setObjectName("frameMed")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameMed)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameBusiness = QtWidgets.QFrame(self.frameMed)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameBusiness.sizePolicy().hasHeightForWidth())
        self.frameBusiness.setSizePolicy(sizePolicy)
        self.frameBusiness.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBusiness.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameBusiness.setLineWidth(0)
        self.frameBusiness.setObjectName("frameBusiness")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameBusiness)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.QcbProject = QtWidgets.QComboBox(self.frameBusiness)
        self.QcbProject.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbProject.setFont(font)
        self.QcbProject.setObjectName("QcbProject")
        self.verticalLayout_2.addWidget(self.QcbProject)
        self.frameBusiness2Shots = QtWidgets.QFrame(self.frameBusiness)
        self.frameBusiness2Shots.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBusiness2Shots.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBusiness2Shots.setObjectName("frameBusiness2Shots")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frameBusiness2Shots)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.QcbExtend1 = QtWidgets.QComboBox(self.frameBusiness2Shots)
        self.QcbExtend1.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbExtend1.setFont(font)
        self.QcbExtend1.setObjectName("QcbExtend1")
        self.horizontalLayout_3.addWidget(self.QcbExtend1)
        self.QcbExtend2 = QtWidgets.QComboBox(self.frameBusiness2Shots)
        self.QcbExtend2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbExtend2.setFont(font)
        self.QcbExtend2.setObjectName("QcbExtend2")
        self.horizontalLayout_3.addWidget(self.QcbExtend2)
        self.verticalLayout_2.addWidget(self.frameBusiness2Shots)
        self.QcbCategory = QtWidgets.QComboBox(self.frameBusiness)
        self.QcbCategory.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbCategory.setFont(font)
        self.QcbCategory.setObjectName("QcbCategory")
        self.verticalLayout_2.addWidget(self.QcbCategory)
        self.QlwTask = QtWidgets.QListWidget(self.frameBusiness)
        self.QlwTask.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwTask.setFont(font)
        self.QlwTask.setObjectName("QlwTask")
        self.verticalLayout_2.addWidget(self.QlwTask)
        self.QcbBusiness = QtWidgets.QComboBox(self.frameBusiness)
        self.QcbBusiness.setMinimumSize(QtCore.QSize(0, 0))
        self.QcbBusiness.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbBusiness.setFont(font)
        self.QcbBusiness.setObjectName("QcbBusiness")
        self.verticalLayout_2.addWidget(self.QcbBusiness)
        self.horizontalLayout_2.addWidget(self.frameBusiness)
        self.tabView = QtWidgets.QTabWidget(self.frameMed)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabView.setFont(font)
        self.tabView.setObjectName("tabView")
        self.tabAni = QtWidgets.QWidget()
        self.tabAni.setObjectName("tabAni")
        self.gridLayout = QtWidgets.QGridLayout(self.tabAni)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.QlwAniVersion = QtWidgets.QListWidget(self.tabAni)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QlwAniVersion.sizePolicy().hasHeightForWidth())
        self.QlwAniVersion.setSizePolicy(sizePolicy)
        self.QlwAniVersion.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwAniVersion.setFont(font)
        self.QlwAniVersion.setObjectName("QlwAniVersion")
        self.gridLayout.addWidget(self.QlwAniVersion, 1, 1, 1, 1)
        self.vlAni = QtWidgets.QVBoxLayout()
        self.vlAni.setSpacing(5)
        self.vlAni.setContentsMargins(-1, -1, 0, -1)
        self.vlAni.setObjectName("vlAni")
        self.vlAlembic = QtWidgets.QVBoxLayout()
        self.vlAlembic.setSpacing(5)
        self.vlAlembic.setObjectName("vlAlembic")
        self.label_2 = QtWidgets.QLabel(self.tabAni)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.vlAlembic.addWidget(self.label_2)
        self.QlwAniCharacter = QtWidgets.QListWidget(self.tabAni)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwAniCharacter.setFont(font)
        self.QlwAniCharacter.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.QlwAniCharacter.setObjectName("QlwAniCharacter")
        self.vlAlembic.addWidget(self.QlwAniCharacter)
        self.label_3 = QtWidgets.QLabel(self.tabAni)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.vlAlembic.addWidget(self.label_3)
        self.QlwAniProp = QtWidgets.QListWidget(self.tabAni)
        self.QlwAniProp.setMinimumSize(QtCore.QSize(0, 0))
        self.QlwAniProp.setMaximumSize(QtCore.QSize(16777215, 160))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwAniProp.setFont(font)
        self.QlwAniProp.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.QlwAniProp.setObjectName("QlwAniProp")
        self.vlAlembic.addWidget(self.QlwAniProp)
        self.vlAni.addLayout(self.vlAlembic)
        self.vlAniScene = QtWidgets.QVBoxLayout()
        self.vlAniScene.setSpacing(5)
        self.vlAniScene.setObjectName("vlAniScene")
        self.label_4 = QtWidgets.QLabel(self.tabAni)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.vlAniScene.addWidget(self.label_4)
        self.QlwAniScene = QtWidgets.QListWidget(self.tabAni)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwAniScene.setFont(font)
        self.QlwAniScene.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.QlwAniScene.setObjectName("QlwAniScene")
        self.vlAniScene.addWidget(self.QlwAniScene)
        self.vlAni.addLayout(self.vlAniScene)
        self.vlAni.setStretch(0, 3)
        self.vlAni.setStretch(1, 1)
        self.gridLayout.addLayout(self.vlAni, 0, 0, 2, 1)
        self.label_5 = QtWidgets.QLabel(self.tabAni)
        self.label_5.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.tabView.addTab(self.tabAni, "")
        self.horizontalLayout_2.addWidget(self.tabView)
        self.tabEdit = QtWidgets.QTabWidget(self.frameMed)
        self.tabEdit.setMaximumSize(QtCore.QSize(320, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabEdit.setFont(font)
        self.tabEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabEdit.setObjectName("tabEdit")
        self.tabArchive = QtWidgets.QWidget()
        self.tabArchive.setObjectName("tabArchive")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabArchive)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.QlwArchive = QtWidgets.QListWidget(self.tabArchive)
        self.QlwArchive.setFocusPolicy(QtCore.Qt.TabFocus)
        self.QlwArchive.setObjectName("QlwArchive")
        self.gridLayout_2.addWidget(self.QlwArchive, 0, 0, 1, 3)
        self.QpbOpen = QtWidgets.QPushButton(self.tabArchive)
        self.QpbOpen.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbOpen.setFont(font)
        self.QpbOpen.setObjectName("QpbOpen")
        self.gridLayout_2.addWidget(self.QpbOpen, 1, 0, 1, 1)
        self.QpbSave = QtWidgets.QPushButton(self.tabArchive)
        self.QpbSave.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbSave.setFont(font)
        self.QpbSave.setObjectName("QpbSave")
        self.gridLayout_2.addWidget(self.QpbSave, 1, 1, 1, 1)
        self.QpbWork = QtWidgets.QPushButton(self.tabArchive)
        self.QpbWork.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbWork.setFont(font)
        self.QpbWork.setObjectName("QpbWork")
        self.gridLayout_2.addWidget(self.QpbWork, 1, 2, 1, 1)
        self.tabEdit.addTab(self.tabArchive, "")
        self.tabAssembly = QtWidgets.QWidget()
        self.tabAssembly.setObjectName("tabAssembly")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabAssembly)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line_2 = QtWidgets.QFrame(self.tabAssembly)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 1, 0, 1, 3)
        self.label_11 = QtWidgets.QLabel(self.tabAssembly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.tabAssembly)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 3, 0, 1, 3)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.QcbResolution = QtWidgets.QCheckBox(self.tabAssembly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbResolution.setFont(font)
        self.QcbResolution.setChecked(True)
        self.QcbResolution.setObjectName("QcbResolution")
        self.verticalLayout_16.addWidget(self.QcbResolution)
        self.QcbSpeed = QtWidgets.QCheckBox(self.tabAssembly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbSpeed.setFont(font)
        self.QcbSpeed.setChecked(True)
        self.QcbSpeed.setObjectName("QcbSpeed")
        self.verticalLayout_16.addWidget(self.QcbSpeed)
        self.QcbRange = QtWidgets.QCheckBox(self.tabAssembly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbRange.setFont(font)
        self.QcbRange.setChecked(True)
        self.QcbRange.setObjectName("QcbRange")
        self.verticalLayout_16.addWidget(self.QcbRange)
        self.gridLayout_4.addLayout(self.verticalLayout_16, 12, 1, 1, 2)
        self.groupBoxMerge = QtWidgets.QGroupBox(self.tabAssembly)
        self.groupBoxMerge.setTitle("")
        self.groupBoxMerge.setObjectName("groupBoxMerge")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxMerge)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.QrbMergeReplace = QtWidgets.QRadioButton(self.groupBoxMerge)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbMergeReplace.setFont(font)
        self.QrbMergeReplace.setChecked(True)
        self.QrbMergeReplace.setObjectName("QrbMergeReplace")
        self.verticalLayout_3.addWidget(self.QrbMergeReplace)
        self.QrbMergeCombine = QtWidgets.QRadioButton(self.groupBoxMerge)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbMergeCombine.setFont(font)
        self.QrbMergeCombine.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.QrbMergeCombine.setChecked(False)
        self.QrbMergeCombine.setObjectName("QrbMergeCombine")
        self.verticalLayout_3.addWidget(self.QrbMergeCombine)
        self.QrbMergeAlembic = QtWidgets.QRadioButton(self.groupBoxMerge)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbMergeAlembic.setFont(font)
        self.QrbMergeAlembic.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.QrbMergeAlembic.setObjectName("QrbMergeAlembic")
        self.verticalLayout_3.addWidget(self.QrbMergeAlembic)
        self.gridLayout_4.addWidget(self.groupBoxMerge, 0, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 15, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tabAssembly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.groupBoxImport = QtWidgets.QGroupBox(self.tabAssembly)
        self.groupBoxImport.setTitle("")
        self.groupBoxImport.setObjectName("groupBoxImport")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBoxImport)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.QrbImportAll = QtWidgets.QRadioButton(self.groupBoxImport)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbImportAll.setFont(font)
        self.QrbImportAll.setChecked(False)
        self.QrbImportAll.setObjectName("QrbImportAll")
        self.horizontalLayout_4.addWidget(self.QrbImportAll)
        self.QrbImportSel = QtWidgets.QRadioButton(self.groupBoxImport)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbImportSel.setFont(font)
        self.QrbImportSel.setChecked(True)
        self.QrbImportSel.setObjectName("QrbImportSel")
        self.horizontalLayout_4.addWidget(self.QrbImportSel)
        self.gridLayout_4.addWidget(self.groupBoxImport, 2, 1, 1, 2)
        self.QpbMerge = QtWidgets.QPushButton(self.tabAssembly)
        self.QpbMerge.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbMerge.setFont(font)
        self.QpbMerge.setObjectName("QpbMerge")
        self.gridLayout_4.addWidget(self.QpbMerge, 16, 0, 1, 3)
        self.QcbBlendshape = QtWidgets.QCheckBox(self.tabAssembly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbBlendshape.setFont(font)
        self.QcbBlendshape.setChecked(False)
        self.QcbBlendshape.setObjectName("QcbBlendshape")
        self.gridLayout_4.addWidget(self.QcbBlendshape, 6, 1, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.tabAssembly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 12, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tabAssembly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.line_1 = QtWidgets.QFrame(self.tabAssembly)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_1.setLineWidth(2)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.gridLayout_4.addWidget(self.line_1, 11, 0, 1, 3)
        self.label_16 = QtWidgets.QLabel(self.tabAssembly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 6, 0, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.QcbCharacter = QtWidgets.QCheckBox(self.tabAssembly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbCharacter.setFont(font)
        self.QcbCharacter.setChecked(True)
        self.QcbCharacter.setObjectName("QcbCharacter")
        self.verticalLayout_15.addWidget(self.QcbCharacter)
        self.QcbProp = QtWidgets.QCheckBox(self.tabAssembly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbProp.setFont(font)
        self.QcbProp.setObjectName("QcbProp")
        self.verticalLayout_15.addWidget(self.QcbProp)
        self.QcbScene = QtWidgets.QCheckBox(self.tabAssembly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbScene.setFont(font)
        self.QcbScene.setObjectName("QcbScene")
        self.verticalLayout_15.addWidget(self.QcbScene)
        self.QcbCamera = QtWidgets.QCheckBox(self.tabAssembly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbCamera.setFont(font)
        self.QcbCamera.setChecked(True)
        self.QcbCamera.setObjectName("QcbCamera")
        self.verticalLayout_15.addWidget(self.QcbCamera)
        self.gridLayout_4.addLayout(self.verticalLayout_15, 4, 1, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.tabAssembly)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 5, 0, 1, 3)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_4.setColumnStretch(2, 1)
        self.tabEdit.addTab(self.tabAssembly, "")
        self.tabNcache = QtWidgets.QWidget()
        self.tabNcache.setObjectName("tabNcache")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabNcache)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.QdspEvaluateEvery = QtWidgets.QDoubleSpinBox(self.tabNcache)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QdspEvaluateEvery.setFont(font)
        self.QdspEvaluateEvery.setDecimals(4)
        self.QdspEvaluateEvery.setMaximum(1000.0)
        self.QdspEvaluateEvery.setProperty("value", 1.0)
        self.QdspEvaluateEvery.setObjectName("QdspEvaluateEvery")
        self.gridLayout_3.addWidget(self.QdspEvaluateEvery, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tabNcache)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.QdsbStart = QtWidgets.QDoubleSpinBox(self.tabNcache)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QdsbStart.sizePolicy().hasHeightForWidth())
        self.QdsbStart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QdsbStart.setFont(font)
        self.QdsbStart.setDecimals(2)
        self.QdsbStart.setMinimum(-999.0)
        self.QdsbStart.setMaximum(9999.0)
        self.QdsbStart.setProperty("value", 50.0)
        self.QdsbStart.setObjectName("QdsbStart")
        self.gridLayout_3.addWidget(self.QdsbStart, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tabNcache)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.QdsbEnd = QtWidgets.QDoubleSpinBox(self.tabNcache)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QdsbEnd.sizePolicy().hasHeightForWidth())
        self.QdsbEnd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QdsbEnd.setFont(font)
        self.QdsbEnd.setDecimals(2)
        self.QdsbEnd.setMinimum(-999.0)
        self.QdsbEnd.setMaximum(9999.0)
        self.QdsbEnd.setProperty("value", 124.0)
        self.QdsbEnd.setObjectName("QdsbEnd")
        self.gridLayout_3.addWidget(self.QdsbEnd, 0, 2, 1, 1)
        self.QpbNcache = QtWidgets.QPushButton(self.tabNcache)
        self.QpbNcache.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbNcache.setFont(font)
        self.QpbNcache.setObjectName("QpbNcache")
        self.gridLayout_3.addWidget(self.QpbNcache, 9, 0, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.tabNcache)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tabNcache)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 3, 0, 1, 3)
        self.QsbSaveEvery = QtWidgets.QSpinBox(self.tabNcache)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QsbSaveEvery.setFont(font)
        self.QsbSaveEvery.setMaximum(100)
        self.QsbSaveEvery.setProperty("value", 1)
        self.QsbSaveEvery.setObjectName("QsbSaveEvery")
        self.gridLayout_3.addWidget(self.QsbSaveEvery, 2, 1, 1, 1)
        self.QlwHairNode = QtWidgets.QListWidget(self.tabNcache)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwHairNode.setFont(font)
        self.QlwHairNode.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.QlwHairNode.setObjectName("QlwHairNode")
        self.gridLayout_3.addWidget(self.QlwHairNode, 5, 0, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.tabNcache)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 4, 0, 1, 3)
        self.label_14 = QtWidgets.QLabel(self.tabNcache)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 6, 2, 1, 1)
        self.QlwClothNode = QtWidgets.QListWidget(self.tabNcache)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwClothNode.setFont(font)
        self.QlwClothNode.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.QlwClothNode.setObjectName("QlwClothNode")
        self.gridLayout_3.addWidget(self.QlwClothNode, 7, 0, 2, 3)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout_3.setRowStretch(5, 3)
        self.gridLayout_3.setRowStretch(7, 2)
        self.tabEdit.addTab(self.tabNcache, "")
        self.horizontalLayout_2.addWidget(self.tabEdit)
        self.verticalLayout.addWidget(self.frameMed)
        self.hlBottom = QtWidgets.QHBoxLayout()
        self.hlBottom.setSpacing(5)
        self.hlBottom.setContentsMargins(-1, -1, -1, 0)
        self.hlBottom.setObjectName("hlBottom")
        self.version = QtWidgets.QLabel(MergeWin)
        self.version.setMinimumSize(QtCore.QSize(0, 24))
        self.version.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.version.setFont(font)
        self.version.setStyleSheet("color: rgb(150, 150, 150);")
        self.version.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.version.setObjectName("version")
        self.hlBottom.addWidget(self.version)
        self.label = QtWidgets.QLabel(MergeWin)
        self.label.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.hlBottom.addWidget(self.label)
        self.verticalLayout.addLayout(self.hlBottom)

        self.retranslateUi(MergeWin)
        self.tabView.setCurrentIndex(0)
        self.tabEdit.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MergeWin)

    def retranslateUi(self, MergeWin):
        MergeWin.setWindowTitle(QtWidgets.QApplication.translate("MergeWin", "Form", None, -1))
        self.QpbRefresh.setText(QtWidgets.QApplication.translate("MergeWin", "刷新界面", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MergeWin", "角色", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MergeWin", "道具", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MergeWin", "场景", None, -1))
        self.tabView.setTabText(self.tabView.indexOf(self.tabAni), QtWidgets.QApplication.translate("MergeWin", "Ani", None, -1))
        self.QpbOpen.setText(QtWidgets.QApplication.translate("MergeWin", "打开文件", None, -1))
        self.QpbSave.setText(QtWidgets.QApplication.translate("MergeWin", "保存当前", None, -1))
        self.QpbWork.setText(QtWidgets.QApplication.translate("MergeWin", "工程新版", None, -1))
        self.tabEdit.setTabText(self.tabEdit.indexOf(self.tabArchive), QtWidgets.QApplication.translate("MergeWin", "存档", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MergeWin", "导入元素：", None, -1))
        self.QcbResolution.setText(QtWidgets.QApplication.translate("MergeWin", "渲染尺寸", None, -1))
        self.QcbSpeed.setText(QtWidgets.QApplication.translate("MergeWin", "播放速度", None, -1))
        self.QcbRange.setText(QtWidgets.QApplication.translate("MergeWin", "起始结束帧", None, -1))
        self.QrbMergeReplace.setText(QtWidgets.QApplication.translate("MergeWin", "替换", None, -1))
        self.QrbMergeCombine.setText(QtWidgets.QApplication.translate("MergeWin", "组合", None, -1))
        self.QrbMergeAlembic.setText(QtWidgets.QApplication.translate("MergeWin", "缓存", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MergeWin", "合并模式：", None, -1))
        self.QrbImportAll.setText(QtWidgets.QApplication.translate("MergeWin", "所有", None, -1))
        self.QrbImportSel.setText(QtWidgets.QApplication.translate("MergeWin", "选择", None, -1))
        self.QpbMerge.setText(QtWidgets.QApplication.translate("MergeWin", "执行", None, -1))
        self.QcbBlendshape.setText(QtWidgets.QApplication.translate("MergeWin", "创建融合变形节点", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MergeWin", "场景预设：", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MergeWin", "选择模式：", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MergeWin", "自动关联：", None, -1))
        self.QcbCharacter.setText(QtWidgets.QApplication.translate("MergeWin", "角色", None, -1))
        self.QcbProp.setText(QtWidgets.QApplication.translate("MergeWin", "道具", None, -1))
        self.QcbScene.setText(QtWidgets.QApplication.translate("MergeWin", "场景", None, -1))
        self.QcbCamera.setText(QtWidgets.QApplication.translate("MergeWin", "摄像机", None, -1))
        self.tabEdit.setTabText(self.tabEdit.indexOf(self.tabAssembly), QtWidgets.QApplication.translate("MergeWin", "组装", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MergeWin", "求值频率：", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MergeWin", "开始/结束：", None, -1))
        self.QpbNcache.setText(QtWidgets.QApplication.translate("MergeWin", "执行", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MergeWin", "保存频率：", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MergeWin", "毛发", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MergeWin", "布料", None, -1))
        self.tabEdit.setTabText(self.tabEdit.indexOf(self.tabNcache), QtWidgets.QApplication.translate("MergeWin", "缓存", None, -1))
        self.version.setText(QtWidgets.QApplication.translate("MergeWin", "版本", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MergeWin", "提示", None, -1))

