# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lgtMergeWindow.ui'
#
# Created: Sun Aug 28 21:40:59 2022
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MergeWin(object):
    def setupUi(self, MergeWin):
        MergeWin.setObjectName("MergeWin")
        MergeWin.resize(1174, 725)
        self.verticalLayout = QtWidgets.QVBoxLayout(MergeWin)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameTop = QtWidgets.QFrame(MergeWin)
        self.frameTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTop.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameTop.setObjectName("frameTop")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameTop)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.QpbRefresh = QtWidgets.QPushButton(self.frameTop)
        self.QpbRefresh.setMinimumSize(QtCore.QSize(75, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbRefresh.setFont(font)
        self.QpbRefresh.setObjectName("QpbRefresh")
        self.horizontalLayout.addWidget(self.QpbRefresh)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frameTop)
        self.frameMed = QtWidgets.QFrame(MergeWin)
        self.frameMed.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMed.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameMed.setObjectName("frameMed")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameMed)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameBusiness = QtWidgets.QFrame(self.frameMed)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameBusiness.sizePolicy().hasHeightForWidth())
        self.frameBusiness.setSizePolicy(sizePolicy)
        self.frameBusiness.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBusiness.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameBusiness.setLineWidth(0)
        self.frameBusiness.setObjectName("frameBusiness")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameBusiness)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.QcbProject = QtWidgets.QComboBox(self.frameBusiness)
        self.QcbProject.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbProject.setFont(font)
        self.QcbProject.setObjectName("QcbProject")
        self.verticalLayout_2.addWidget(self.QcbProject)
        self.frameBusiness2Shots = QtWidgets.QFrame(self.frameBusiness)
        self.frameBusiness2Shots.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBusiness2Shots.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBusiness2Shots.setObjectName("frameBusiness2Shots")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frameBusiness2Shots)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.QcbExtend1 = QtWidgets.QComboBox(self.frameBusiness2Shots)
        self.QcbExtend1.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbExtend1.setFont(font)
        self.QcbExtend1.setObjectName("QcbExtend1")
        self.horizontalLayout_3.addWidget(self.QcbExtend1)
        self.QcbExtend2 = QtWidgets.QComboBox(self.frameBusiness2Shots)
        self.QcbExtend2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbExtend2.setFont(font)
        self.QcbExtend2.setObjectName("QcbExtend2")
        self.horizontalLayout_3.addWidget(self.QcbExtend2)
        self.verticalLayout_2.addWidget(self.frameBusiness2Shots)
        self.QcbCategory = QtWidgets.QComboBox(self.frameBusiness)
        self.QcbCategory.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbCategory.setFont(font)
        self.QcbCategory.setObjectName("QcbCategory")
        self.verticalLayout_2.addWidget(self.QcbCategory)
        self.QlwTask = QtWidgets.QListWidget(self.frameBusiness)
        self.QlwTask.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwTask.setFont(font)
        self.QlwTask.setObjectName("QlwTask")
        self.verticalLayout_2.addWidget(self.QlwTask)
        self.QcbBusiness = QtWidgets.QComboBox(self.frameBusiness)
        self.QcbBusiness.setMinimumSize(QtCore.QSize(0, 0))
        self.QcbBusiness.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbBusiness.setFont(font)
        self.QcbBusiness.setObjectName("QcbBusiness")
        self.verticalLayout_2.addWidget(self.QcbBusiness)
        self.horizontalLayout_2.addWidget(self.frameBusiness)
        self.tabView = QtWidgets.QTabWidget(self.frameMed)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabView.setFont(font)
        self.tabView.setObjectName("tabView")
        self.tabAni = QtWidgets.QWidget()
        self.tabAni.setObjectName("tabAni")
        self.gridLayout = QtWidgets.QGridLayout(self.tabAni)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.QlwAniVersion = QtWidgets.QListWidget(self.tabAni)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QlwAniVersion.sizePolicy().hasHeightForWidth())
        self.QlwAniVersion.setSizePolicy(sizePolicy)
        self.QlwAniVersion.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwAniVersion.setFont(font)
        self.QlwAniVersion.setObjectName("QlwAniVersion")
        self.gridLayout.addWidget(self.QlwAniVersion, 1, 1, 1, 1)
        self.vlAni = QtWidgets.QVBoxLayout()
        self.vlAni.setSpacing(5)
        self.vlAni.setContentsMargins(-1, -1, 0, -1)
        self.vlAni.setObjectName("vlAni")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.tabAni)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.QlwAniCharacter = QtWidgets.QListWidget(self.tabAni)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwAniCharacter.setFont(font)
        self.QlwAniCharacter.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.QlwAniCharacter.setObjectName("QlwAniCharacter")
        self.verticalLayout_7.addWidget(self.QlwAniCharacter)
        self.vlAni.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.tabAni)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.QlwAniProp = QtWidgets.QListWidget(self.tabAni)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwAniProp.setFont(font)
        self.QlwAniProp.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.QlwAniProp.setObjectName("QlwAniProp")
        self.verticalLayout_6.addWidget(self.QlwAniProp)
        self.vlAni.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tabAni)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.QlwAniScene = QtWidgets.QListWidget(self.tabAni)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwAniScene.setFont(font)
        self.QlwAniScene.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.QlwAniScene.setObjectName("QlwAniScene")
        self.verticalLayout_4.addWidget(self.QlwAniScene)
        self.vlAni.addLayout(self.verticalLayout_4)
        self.vlAni.setStretch(0, 2)
        self.vlAni.setStretch(1, 1)
        self.vlAni.setStretch(2, 1)
        self.gridLayout.addLayout(self.vlAni, 0, 0, 2, 1)
        self.label_5 = QtWidgets.QLabel(self.tabAni)
        self.label_5.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.tabView.addTab(self.tabAni, "")
        self.tabEfx = QtWidgets.QWidget()
        self.tabEfx.setObjectName("tabEfx")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tabEfx)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.QlwEfxCache = QtWidgets.QListWidget(self.tabEfx)
        self.QlwEfxCache.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.QlwEfxCache.setObjectName("QlwEfxCache")
        self.horizontalLayout_6.addWidget(self.QlwEfxCache)
        self.QlwEfxVersion = QtWidgets.QListWidget(self.tabEfx)
        self.QlwEfxVersion.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwEfxVersion.setFont(font)
        self.QlwEfxVersion.setObjectName("QlwEfxVersion")
        self.horizontalLayout_6.addWidget(self.QlwEfxVersion)
        self.tabView.addTab(self.tabEfx, "")
        self.tabSim = QtWidgets.QWidget()
        self.tabSim.setObjectName("tabSim")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabSim)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.vlSim = QtWidgets.QVBoxLayout()
        self.vlSim.setSpacing(5)
        self.vlSim.setContentsMargins(-1, -1, 0, -1)
        self.vlSim.setObjectName("vlSim")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.tabSim)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.QlwSimCharacter = QtWidgets.QListWidget(self.tabSim)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwSimCharacter.setFont(font)
        self.QlwSimCharacter.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.QlwSimCharacter.setObjectName("QlwSimCharacter")
        self.verticalLayout_8.addWidget(self.QlwSimCharacter)
        self.vlSim.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.tabSim)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.QlwSimProp = QtWidgets.QListWidget(self.tabSim)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwSimProp.setFont(font)
        self.QlwSimProp.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.QlwSimProp.setObjectName("QlwSimProp")
        self.verticalLayout_9.addWidget(self.QlwSimProp)
        self.vlSim.addLayout(self.verticalLayout_9)
        self.vlSim.setStretch(0, 3)
        self.vlSim.setStretch(1, 2)
        self.gridLayout_3.addLayout(self.vlSim, 0, 0, 2, 1)
        self.label_9 = QtWidgets.QLabel(self.tabSim)
        self.label_9.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 1, 1, 1)
        self.QlwSimVersion = QtWidgets.QListWidget(self.tabSim)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QlwSimVersion.sizePolicy().hasHeightForWidth())
        self.QlwSimVersion.setSizePolicy(sizePolicy)
        self.QlwSimVersion.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwSimVersion.setFont(font)
        self.QlwSimVersion.setObjectName("QlwSimVersion")
        self.gridLayout_3.addWidget(self.QlwSimVersion, 1, 1, 1, 1)
        self.tabView.addTab(self.tabSim, "")
        self.horizontalLayout_2.addWidget(self.tabView)
        self.tabEdit = QtWidgets.QTabWidget(self.frameMed)
        self.tabEdit.setMaximumSize(QtCore.QSize(320, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabEdit.setFont(font)
        self.tabEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabEdit.setObjectName("tabEdit")
        self.tabArchive = QtWidgets.QWidget()
        self.tabArchive.setObjectName("tabArchive")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabArchive)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.QlwArchive = QtWidgets.QListWidget(self.tabArchive)
        self.QlwArchive.setObjectName("QlwArchive")
        self.gridLayout_2.addWidget(self.QlwArchive, 0, 0, 1, 3)
        self.QpbOpen = QtWidgets.QPushButton(self.tabArchive)
        self.QpbOpen.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbOpen.setFont(font)
        self.QpbOpen.setObjectName("QpbOpen")
        self.gridLayout_2.addWidget(self.QpbOpen, 1, 0, 1, 1)
        self.QpbSave = QtWidgets.QPushButton(self.tabArchive)
        self.QpbSave.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbSave.setFont(font)
        self.QpbSave.setObjectName("QpbSave")
        self.gridLayout_2.addWidget(self.QpbSave, 1, 1, 1, 1)
        self.QpbWork = QtWidgets.QPushButton(self.tabArchive)
        self.QpbWork.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbWork.setFont(font)
        self.QpbWork.setObjectName("QpbWork")
        self.gridLayout_2.addWidget(self.QpbWork, 1, 2, 1, 1)
        self.tabEdit.addTab(self.tabArchive, "")
        self.tabMerge = QtWidgets.QWidget()
        self.tabMerge.setObjectName("tabMerge")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabMerge)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gbScene = QtWidgets.QGroupBox(self.tabMerge)
        self.gbScene.setTitle("")
        self.gbScene.setObjectName("gbScene")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbScene)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.QrbSceneAR = QtWidgets.QRadioButton(self.gbScene)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbSceneAR.setFont(font)
        self.QrbSceneAR.setChecked(True)
        self.QrbSceneAR.setObjectName("QrbSceneAR")
        self.verticalLayout_3.addWidget(self.QrbSceneAR)
        self.QrbSceneRN = QtWidgets.QRadioButton(self.gbScene)
        self.QrbSceneRN.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbSceneRN.setFont(font)
        self.QrbSceneRN.setCheckable(True)
        self.QrbSceneRN.setObjectName("QrbSceneRN")
        self.verticalLayout_3.addWidget(self.QrbSceneRN)
        self.gridLayout_4.addWidget(self.gbScene, 2, 1, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.tabMerge)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.line_1 = QtWidgets.QFrame(self.tabMerge)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_1.setLineWidth(2)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.gridLayout_4.addWidget(self.line_1, 1, 0, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.tabMerge)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.QpbMerge = QtWidgets.QPushButton(self.tabMerge)
        self.QpbMerge.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbMerge.setFont(font)
        self.QpbMerge.setObjectName("QpbMerge")
        self.gridLayout_4.addWidget(self.QpbMerge, 7, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 5, 0, 1, 1)
        self.QcbMerge = QtWidgets.QComboBox(self.tabMerge)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbMerge.setFont(font)
        self.QcbMerge.setObjectName("QcbMerge")
        self.gridLayout_4.addWidget(self.QcbMerge, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.tabMerge)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 3, 0, 1, 3)
        self.label_12 = QtWidgets.QLabel(self.tabMerge)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 4, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tabMerge)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.QcbResolution = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbResolution.setFont(font)
        self.QcbResolution.setChecked(True)
        self.QcbResolution.setObjectName("QcbResolution")
        self.verticalLayout_5.addWidget(self.QcbResolution)
        self.QcbSpeed = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbSpeed.setFont(font)
        self.QcbSpeed.setChecked(True)
        self.QcbSpeed.setObjectName("QcbSpeed")
        self.verticalLayout_5.addWidget(self.QcbSpeed)
        self.QcbRange = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbRange.setFont(font)
        self.QcbRange.setChecked(True)
        self.QcbRange.setObjectName("QcbRange")
        self.verticalLayout_5.addWidget(self.QcbRange)
        self.gridLayout_4.addWidget(self.groupBox, 4, 1, 1, 2)
        self.tabEdit.addTab(self.tabMerge, "")
        self.horizontalLayout_2.addWidget(self.tabEdit)
        self.verticalLayout.addWidget(self.frameMed)
        self.hlBottom = QtWidgets.QHBoxLayout()
        self.hlBottom.setSpacing(5)
        self.hlBottom.setContentsMargins(-1, -1, -1, 0)
        self.hlBottom.setObjectName("hlBottom")
        self.version = QtWidgets.QLabel(MergeWin)
        self.version.setMinimumSize(QtCore.QSize(0, 24))
        self.version.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.version.setFont(font)
        self.version.setStyleSheet("color: rgb(150, 150, 150);")
        self.version.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.version.setObjectName("version")
        self.hlBottom.addWidget(self.version)
        self.label = QtWidgets.QLabel(MergeWin)
        self.label.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.hlBottom.addWidget(self.label)
        self.verticalLayout.addLayout(self.hlBottom)

        self.retranslateUi(MergeWin)
        self.tabView.setCurrentIndex(0)
        self.tabEdit.setCurrentIndex(0)
        self.QcbMerge.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MergeWin)

    def retranslateUi(self, MergeWin):
        MergeWin.setWindowTitle(QtWidgets.QApplication.translate("MergeWin", "Form", None, -1))
        self.QpbRefresh.setText(QtWidgets.QApplication.translate("MergeWin", "刷新界面", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MergeWin", "角色", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MergeWin", "道具", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MergeWin", "场景", None, -1))
        self.tabView.setTabText(self.tabView.indexOf(self.tabAni), QtWidgets.QApplication.translate("MergeWin", "Ani", None, -1))
        self.tabView.setTabText(self.tabView.indexOf(self.tabEfx), QtWidgets.QApplication.translate("MergeWin", "Efx", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MergeWin", "角色", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MergeWin", "道具", None, -1))
        self.tabView.setTabText(self.tabView.indexOf(self.tabSim), QtWidgets.QApplication.translate("MergeWin", "Sim", None, -1))
        self.QpbOpen.setText(QtWidgets.QApplication.translate("MergeWin", "打开文件", None, -1))
        self.QpbSave.setText(QtWidgets.QApplication.translate("MergeWin", "保存当前", None, -1))
        self.QpbWork.setText(QtWidgets.QApplication.translate("MergeWin", "工程新版", None, -1))
        self.tabEdit.setTabText(self.tabEdit.indexOf(self.tabArchive), QtWidgets.QApplication.translate("MergeWin", "存档", None, -1))
        self.QrbSceneAR.setText(QtWidgets.QApplication.translate("MergeWin", "场景AR以原有直接导入", None, -1))
        self.QrbSceneRN.setText(QtWidgets.QApplication.translate("MergeWin", "场景AR以引用方式创建", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MergeWin", "场景模式：", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MergeWin", "渲染模式：", None, -1))
        self.QpbMerge.setText(QtWidgets.QApplication.translate("MergeWin", "执行", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MergeWin", "场景预设：", None, -1))
        self.QcbResolution.setText(QtWidgets.QApplication.translate("MergeWin", "渲染尺寸", None, -1))
        self.QcbSpeed.setText(QtWidgets.QApplication.translate("MergeWin", "播放速度", None, -1))
        self.QcbRange.setText(QtWidgets.QApplication.translate("MergeWin", "起始结束帧", None, -1))
        self.tabEdit.setTabText(self.tabEdit.indexOf(self.tabMerge), QtWidgets.QApplication.translate("MergeWin", "组装", None, -1))
        self.version.setText(QtWidgets.QApplication.translate("MergeWin", "版本", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MergeWin", "提示", None, -1))

