# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Study\BaiduSyncdisk\MyStudy\pyside2\ma.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import PyQt5.QtCore as QtCore
import PyQt5.QtGui as QtGui
import PyQt5.QtWidgets  as QtWidgets
#from PyQt5 import QtCore, QtGui, QtWidgets
import os
import packMa
import time

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(820, 412)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 801, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(796, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.progressLayout = QtWidgets.QHBoxLayout()
        self.progressLayout.setObjectName("progressLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.progressLayout.addWidget(self.label_4)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressLayout.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.progressLayout)
        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.pack) # type: ignore
        self.plainTextEdit.textChanged.connect(Form.source) # type: ignore
        self.lineEdit.editingFinished.connect(Form.destination) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ma文件打包工具"))
        self.label_2.setText(_translate("Form", "此插件可以打包任意格式文件或者文件夹，ma文件的引用文件也会被打包"))
        self.label.setText(_translate("Form", "请输入要打包的文件名或文件夹（每行一个文件或一个文件夹）："))
        self.label_3.setText(_translate("Form", "打包目标路径："))
        self.pushButton.setText(_translate("Form", "开始打包"))
        self.label_4.setText(_translate("Form", "打包进度"))
'''
    def pack(self):#类内的函数，这个self没什么含义，只代表一个自身的实例，不是参数
        packMa.main(self.sourcePaths,self.destinationPath)
        while packMa.progress<100:
            self.progressBar.setValue(packMa.progress)
            time.sleep(0.5)
        if packMa.progress==100:
            self.progressBar.setValue(100)
            QtWidgets.QMessageBox.information(self,'提示','打包完成')
        else:
            QtWidgets.QMessageBox.warning(self,'警告','打包失败')
    
    def source(self):
        paths=self.plainTextEdit.toPlainText()
        for path in paths.split('\n'):
            path=path.strip()
            if os.path.exists(path):
                self.sourcePaths.append(path)
    def destination(self):
        path=self.lineEdit.text()
        if os.path.exists(path):
            self.destinationPath=path
        else:
            os.makedirs(path)
    def setProgress(self,value=0):
        if value==0:
            self.progressBar.hide()
        else:
            self.progressBar.show()
        self.progressBar.setValue(value)

    #类变量
    sourcePaths=[]
    destinationPath=''

'''