# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simExportWindow.ui'
#
# Created: Wed May 18 16:54:51 2022
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ExportWin(object):
    def setupUi(self, ExportWin):
        ExportWin.setObjectName("ExportWin")
        ExportWin.resize(1177, 760)
        self.centralwidget = QtWidgets.QWidget(ExportWin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidgetView = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetView.sizePolicy().hasHeightForWidth())
        self.tabWidgetView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidgetView.setFont(font)
        self.tabWidgetView.setObjectName("tabWidgetView")
        self.tabAlembic = QtWidgets.QWidget()
        self.tabAlembic.setObjectName("tabAlembic")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabAlembic)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelSim = QtWidgets.QLabel(self.tabAlembic)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelSim.setFont(font)
        self.labelSim.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelSim.setObjectName("labelSim")
        self.verticalLayout_4.addWidget(self.labelSim)
        self.QlwSim = QtWidgets.QListWidget(self.tabAlembic)
        self.QlwSim.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.QlwSim.setResizeMode(QtWidgets.QListView.Adjust)
        self.QlwSim.setSpacing(5)
        self.QlwSim.setViewMode(QtWidgets.QListView.IconMode)
        self.QlwSim.setObjectName("QlwSim")
        self.verticalLayout_4.addWidget(self.QlwSim)
        self.labelTmp = QtWidgets.QLabel(self.tabAlembic)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTmp.setFont(font)
        self.labelTmp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTmp.setObjectName("labelTmp")
        self.verticalLayout_4.addWidget(self.labelTmp)
        self.QlwTmp = QtWidgets.QListWidget(self.tabAlembic)
        self.QlwTmp.setMaximumSize(QtCore.QSize(16777215, 240))
        self.QlwTmp.setFocusPolicy(QtCore.Qt.NoFocus)
        self.QlwTmp.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.QlwTmp.setResizeMode(QtWidgets.QListView.Adjust)
        self.QlwTmp.setSpacing(5)
        self.QlwTmp.setViewMode(QtWidgets.QListView.IconMode)
        self.QlwTmp.setObjectName("QlwTmp")
        self.verticalLayout_4.addWidget(self.QlwTmp)
        self.tabWidgetView.addTab(self.tabAlembic, "")
        self.horizontalLayout.addWidget(self.tabWidgetView)
        self.tabWidgetEdit = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetEdit.sizePolicy().hasHeightForWidth())
        self.tabWidgetEdit.setSizePolicy(sizePolicy)
        self.tabWidgetEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidgetEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidgetEdit.setFont(font)
        self.tabWidgetEdit.setObjectName("tabWidgetEdit")
        self.tabExport = QtWidgets.QWidget()
        self.tabExport.setObjectName("tabExport")
        self.gridLayout = QtWidgets.QGridLayout(self.tabExport)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabExport)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.QrbExportAll = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbExportAll.setFont(font)
        self.QrbExportAll.setChecked(True)
        self.QrbExportAll.setObjectName("QrbExportAll")
        self.horizontalLayout_3.addWidget(self.QrbExportAll)
        self.QrbExportSel = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbExportSel.setFont(font)
        self.QrbExportSel.setObjectName("QrbExportSel")
        self.horizontalLayout_3.addWidget(self.QrbExportSel)
        self.gridLayout.addWidget(self.groupBox_2, 2, 1, 2, 2)
        self.label_2 = QtWidgets.QLabel(self.tabExport)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 2, 1)
        self.QcbColorSets = QtWidgets.QCheckBox(self.tabExport)
        self.QcbColorSets.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbColorSets.setFont(font)
        self.QcbColorSets.setChecked(False)
        self.QcbColorSets.setObjectName("QcbColorSets")
        self.gridLayout.addWidget(self.QcbColorSets, 8, 1, 1, 2)
        self.QcbEvaluation = QtWidgets.QComboBox(self.tabExport)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbEvaluation.setFont(font)
        self.QcbEvaluation.setObjectName("QcbEvaluation")
        self.QcbEvaluation.addItem("")
        self.QcbEvaluation.addItem("")
        self.QcbEvaluation.addItem("")
        self.gridLayout.addWidget(self.QcbEvaluation, 0, 1, 1, 1)
        self.QdsbAnimationMin = QtWidgets.QDoubleSpinBox(self.tabExport)
        self.QdsbAnimationMin.setEnabled(False)
        self.QdsbAnimationMin.setMaximum(1000.0)
        self.QdsbAnimationMin.setProperty("value", 101.0)
        self.QdsbAnimationMin.setObjectName("QdsbAnimationMin")
        self.gridLayout.addWidget(self.QdsbAnimationMin, 16, 1, 1, 1)
        self.QdsbSimulation = QtWidgets.QDoubleSpinBox(self.tabExport)
        self.QdsbSimulation.setEnabled(False)
        self.QdsbSimulation.setMinimum(-1000.0)
        self.QdsbSimulation.setMaximum(1000.0)
        self.QdsbSimulation.setProperty("value", 50.0)
        self.QdsbSimulation.setObjectName("QdsbSimulation")
        self.gridLayout.addWidget(self.QdsbSimulation, 21, 1, 1, 1)
        self.QdsbHandleMin = QtWidgets.QDoubleSpinBox(self.tabExport)
        self.QdsbHandleMin.setEnabled(False)
        self.QdsbHandleMin.setMinimum(-10.0)
        self.QdsbHandleMin.setMaximum(0.0)
        self.QdsbHandleMin.setProperty("value", -3.0)
        self.QdsbHandleMin.setObjectName("QdsbHandleMin")
        self.gridLayout.addWidget(self.QdsbHandleMin, 19, 1, 1, 1)
        self.QcbCreases = QtWidgets.QCheckBox(self.tabExport)
        self.QcbCreases.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbCreases.setFont(font)
        self.QcbCreases.setChecked(False)
        self.QcbCreases.setObjectName("QcbCreases")
        self.gridLayout.addWidget(self.QcbCreases, 12, 1, 1, 2)
        self.QdsbStep = QtWidgets.QDoubleSpinBox(self.tabExport)
        self.QdsbStep.setEnabled(True)
        self.QdsbStep.setMaximum(10.0)
        self.QdsbStep.setProperty("value", 1.0)
        self.QdsbStep.setObjectName("QdsbStep")
        self.gridLayout.addWidget(self.QdsbStep, 24, 1, 1, 1)
        self.QcbWorld = QtWidgets.QCheckBox(self.tabExport)
        self.QcbWorld.setEnabled(False)
        self.QcbWorld.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbWorld.setFont(font)
        self.QcbWorld.setChecked(True)
        self.QcbWorld.setObjectName("QcbWorld")
        self.gridLayout.addWidget(self.QcbWorld, 10, 1, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.tabExport)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 15, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.tabExport)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.QcbUV = QtWidgets.QCheckBox(self.tabExport)
        self.QcbUV.setEnabled(False)
        self.QcbUV.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbUV.setFont(font)
        self.QcbUV.setChecked(True)
        self.QcbUV.setObjectName("QcbUV")
        self.gridLayout.addWidget(self.QcbUV, 7, 1, 1, 2)
        self.line_5 = QtWidgets.QFrame(self.tabExport)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 29, 0, 1, 3)
        self.QdsbHandleMax = QtWidgets.QDoubleSpinBox(self.tabExport)
        self.QdsbHandleMax.setEnabled(False)
        self.QdsbHandleMax.setMaximum(10.0)
        self.QdsbHandleMax.setProperty("value", 3.0)
        self.QdsbHandleMax.setObjectName("QdsbHandleMax")
        self.gridLayout.addWidget(self.QdsbHandleMax, 19, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tabExport)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 30, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tabExport)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 25, 0, 1, 3)
        self.QdsbAnimationMax = QtWidgets.QDoubleSpinBox(self.tabExport)
        self.QdsbAnimationMax.setMaximum(5000.0)
        self.QdsbAnimationMax.setProperty("value", 124.0)
        self.QdsbAnimationMax.setObjectName("QdsbAnimationMax")
        self.gridLayout.addWidget(self.QdsbAnimationMax, 16, 2, 1, 1)
        self.QcbProject = QtWidgets.QComboBox(self.tabExport)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbProject.setFont(font)
        self.QcbProject.setObjectName("QcbProject")
        self.gridLayout.addWidget(self.QcbProject, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tabExport)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 35, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tabExport)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.tabExport)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 19, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tabExport)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 21, 0, 1, 1)
        self.QcbStrip = QtWidgets.QCheckBox(self.tabExport)
        self.QcbStrip.setEnabled(False)
        self.QcbStrip.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbStrip.setFont(font)
        self.QcbStrip.setChecked(True)
        self.QcbStrip.setObjectName("QcbStrip")
        self.gridLayout.addWidget(self.QcbStrip, 6, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.tabExport)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 16, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tabExport)
        self.label_7.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 24, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.QpbStyle = QtWidgets.QPushButton(self.tabExport)
        self.QpbStyle.setMinimumSize(QtCore.QSize(0, 26))
        self.QpbStyle.setMaximumSize(QtCore.QSize(26, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbStyle.setFont(font)
        self.QpbStyle.setObjectName("QpbStyle")
        self.horizontalLayout_2.addWidget(self.QpbStyle)
        self.QpbExport = QtWidgets.QPushButton(self.tabExport)
        self.QpbExport.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbExport.setFont(font)
        self.QpbExport.setObjectName("QpbExport")
        self.horizontalLayout_2.addWidget(self.QpbExport)
        self.gridLayout.addLayout(self.horizontalLayout_2, 38, 0, 1, 3)
        self.QcbVisibility = QtWidgets.QCheckBox(self.tabExport)
        self.QcbVisibility.setEnabled(False)
        self.QcbVisibility.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbVisibility.setFont(font)
        self.QcbVisibility.setChecked(True)
        self.QcbVisibility.setObjectName("QcbVisibility")
        self.gridLayout.addWidget(self.QcbVisibility, 11, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.tabExport)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.tabExport)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 34, 0, 1, 3)
        self.QcbFaceSets = QtWidgets.QCheckBox(self.tabExport)
        self.QcbFaceSets.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbFaceSets.setFont(font)
        self.QcbFaceSets.setChecked(False)
        self.QcbFaceSets.setObjectName("QcbFaceSets")
        self.gridLayout.addWidget(self.QcbFaceSets, 9, 1, 1, 2)
        self.QcbVersion = QtWidgets.QCheckBox(self.tabExport)
        self.QcbVersion.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbVersion.setFont(font)
        self.QcbVersion.setChecked(True)
        self.QcbVersion.setObjectName("QcbVersion")
        self.gridLayout.addWidget(self.QcbVersion, 26, 1, 1, 2)
        self.QcbDrive = QtWidgets.QComboBox(self.tabExport)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbDrive.setFont(font)
        self.QcbDrive.setObjectName("QcbDrive")
        self.gridLayout.addWidget(self.QcbDrive, 30, 1, 1, 1)
        self.QcbNormals = QtWidgets.QCheckBox(self.tabExport)
        self.QcbNormals.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbNormals.setFont(font)
        self.QcbNormals.setObjectName("QcbNormals")
        self.gridLayout.addWidget(self.QcbNormals, 5, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.tabExport)
        self.label_5.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 14, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 37, 2, 1, 1)
        self.line_1 = QtWidgets.QFrame(self.tabExport)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_1.setLineWidth(2)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.gridLayout.addWidget(self.line_1, 1, 0, 1, 3)
        self.QcbUvSets = QtWidgets.QCheckBox(self.tabExport)
        self.QcbUvSets.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbUvSets.setFont(font)
        self.QcbUvSets.setChecked(False)
        self.QcbUvSets.setObjectName("QcbUvSets")
        self.gridLayout.addWidget(self.QcbUvSets, 13, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.tabExport)
        self.label_13.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 32, 0, 1, 1)
        self.QcbClothNcache = QtWidgets.QCheckBox(self.tabExport)
        self.QcbClothNcache.setEnabled(False)
        self.QcbClothNcache.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbClothNcache.setFont(font)
        self.QcbClothNcache.setChecked(True)
        self.QcbClothNcache.setObjectName("QcbClothNcache")
        self.gridLayout.addWidget(self.QcbClothNcache, 33, 1, 1, 2)
        self.QcbCurveNcache = QtWidgets.QCheckBox(self.tabExport)
        self.QcbCurveNcache.setEnabled(False)
        self.QcbCurveNcache.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbCurveNcache.setFont(font)
        self.QcbCurveNcache.setChecked(True)
        self.QcbCurveNcache.setObjectName("QcbCurveNcache")
        self.gridLayout.addWidget(self.QcbCurveNcache, 32, 1, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.tabExport)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.QrbExClassic = QtWidgets.QRadioButton(self.groupBox)
        self.QrbExClassic.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbExClassic.setFont(font)
        self.QrbExClassic.setChecked(True)
        self.QrbExClassic.setObjectName("QrbExClassic")
        self.verticalLayout_5.addWidget(self.QrbExClassic)
        self.QrbExPrompt = QtWidgets.QRadioButton(self.groupBox)
        self.QrbExPrompt.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbExPrompt.setFont(font)
        self.QrbExPrompt.setObjectName("QrbExPrompt")
        self.verticalLayout_5.addWidget(self.QrbExPrompt)
        self.QrbExClient = QtWidgets.QRadioButton(self.groupBox)
        self.QrbExClient.setEnabled(False)
        self.QrbExClient.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbExClient.setFont(font)
        self.QrbExClient.setObjectName("QrbExClient")
        self.verticalLayout_5.addWidget(self.QrbExClient)
        self.gridLayout.addWidget(self.groupBox, 35, 1, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabExport)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.QrbHDF5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.QrbHDF5.setEnabled(False)
        self.QrbHDF5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbHDF5.setFont(font)
        self.QrbHDF5.setChecked(False)
        self.QrbHDF5.setObjectName("QrbHDF5")
        self.verticalLayout_7.addWidget(self.QrbHDF5)
        self.QrbOgawa = QtWidgets.QRadioButton(self.groupBox_3)
        self.QrbOgawa.setEnabled(False)
        self.QrbOgawa.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbOgawa.setFont(font)
        self.QrbOgawa.setChecked(True)
        self.QrbOgawa.setObjectName("QrbOgawa")
        self.verticalLayout_7.addWidget(self.QrbOgawa)
        self.gridLayout.addWidget(self.groupBox_3, 14, 1, 1, 2)
        self.line = QtWidgets.QFrame(self.tabExport)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 31, 0, 1, 3)
        self.gridLayout.setColumnStretch(0, 1)
        self.tabWidgetEdit.addTab(self.tabExport, "")
        self.tabNote = QtWidgets.QWidget()
        self.tabNote.setObjectName("tabNote")
        self.tabWidgetEdit.addTab(self.tabNote, "")
        self.horizontalLayout.addWidget(self.tabWidgetEdit)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.hlNote = QtWidgets.QHBoxLayout()
        self.hlNote.setSpacing(5)
        self.hlNote.setContentsMargins(-1, -1, -1, 0)
        self.hlNote.setObjectName("hlNote")
        self.frameNote = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameNote.sizePolicy().hasHeightForWidth())
        self.frameNote.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frameNote.setFont(font)
        self.frameNote.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameNote.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameNote.setObjectName("frameNote")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frameNote)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_22 = QtWidgets.QLabel(self.frameNote)
        self.label_22.setMinimumSize(QtCore.QSize(48, 0))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(50, 50, 50);\n"
"background-color: rgb(75, 150, 75);\n"
"padding-bottom: 1px;")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_4.addWidget(self.label_22)
        self.label_20 = QtWidgets.QLabel(self.frameNote)
        self.label_20.setMinimumSize(QtCore.QSize(48, 0))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(50, 50, 50);\n"
"background-color: rgb(0, 150, 150);\n"
"padding-bottom: 1px;\n"
"")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_4.addWidget(self.label_20)
        self.label_25 = QtWidgets.QLabel(self.frameNote)
        self.label_25.setMinimumSize(QtCore.QSize(48, 0))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(50, 50, 50);\n"
"background-color: rgb(214, 128, 109);\n"
"padding-bottom: 1px;\n"
"")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_4.addWidget(self.label_25)
        self.label_23 = QtWidgets.QLabel(self.frameNote)
        self.label_23.setMinimumSize(QtCore.QSize(48, 0))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(50, 50, 50);\n"
"background-color: rgb(150, 75, 150);\n"
"padding-bottom: 1px;")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.frameNote)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(50, 50, 50);\n"
"background-color: rgb(100, 100, 100);")
        self.label_24.setText("")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.label_26 = QtWidgets.QLabel(self.frameNote)
        self.label_26.setMinimumSize(QtCore.QSize(48, 0))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(50, 50, 50);\n"
"background-color: rgb(175, 175, 175);\n"
"padding-bottom: 1px;\n"
"")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_4.addWidget(self.label_26)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.hlNote.addWidget(self.frameNote)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.hlNote.addWidget(self.label)
        self.verticalLayout.addLayout(self.hlNote)
        ExportWin.setCentralWidget(self.centralwidget)

        self.retranslateUi(ExportWin)
        self.tabWidgetView.setCurrentIndex(0)
        self.tabWidgetEdit.setCurrentIndex(0)
        self.QcbEvaluation.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(ExportWin)

    def retranslateUi(self, ExportWin):
        ExportWin.setWindowTitle(QtWidgets.QApplication.translate("ExportWin", "MainWindow", None, -1))
        self.labelSim.setText(QtWidgets.QApplication.translate("ExportWin", "解算", None, -1))
        self.labelTmp.setText(QtWidgets.QApplication.translate("ExportWin", "临时", None, -1))
        self.tabWidgetView.setTabText(self.tabWidgetView.indexOf(self.tabAlembic), QtWidgets.QApplication.translate("ExportWin", "缓存", None, -1))
        self.QrbExportAll.setText(QtWidgets.QApplication.translate("ExportWin", "所有", None, -1))
        self.QrbExportSel.setText(QtWidgets.QApplication.translate("ExportWin", "选择", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("ExportWin", "选择模式：", None, -1))
        self.QcbColorSets.setText(QtWidgets.QApplication.translate("ExportWin", "写入颜色集", None, -1))
        self.QcbEvaluation.setItemText(0, QtWidgets.QApplication.translate("ExportWin", "DG", None, -1))
        self.QcbEvaluation.setItemText(1, QtWidgets.QApplication.translate("ExportWin", "Serial", None, -1))
        self.QcbEvaluation.setItemText(2, QtWidgets.QApplication.translate("ExportWin", "Parallel", None, -1))
        self.QcbCreases.setText(QtWidgets.QApplication.translate("ExportWin", "写入折痕", None, -1))
        self.QcbWorld.setText(QtWidgets.QApplication.translate("ExportWin", "世界空间", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("ExportWin", " 高级选项：", None, -1))
        self.QcbUV.setText(QtWidgets.QApplication.translate("ExportWin", "UV 写入", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("ExportWin", "驱动器号：", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("ExportWin", "输出模式：", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("ExportWin", "手柄时间：", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("ExportWin", "解算时间：", None, -1))
        self.QcbStrip.setText(QtWidgets.QApplication.translate("ExportWin", "去除名称空间", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("ExportWin", "动画时间：", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("ExportWin", "步长：", None, -1))
        self.QpbStyle.setText(QtWidgets.QApplication.translate("ExportWin", "[-]", None, -1))
        self.QpbExport.setText(QtWidgets.QApplication.translate("ExportWin", "执行", None, -1))
        self.QcbVisibility.setText(QtWidgets.QApplication.translate("ExportWin", "写入可见性", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("ExportWin", "求值模式：", None, -1))
        self.QcbFaceSets.setText(QtWidgets.QApplication.translate("ExportWin", "写入面集", None, -1))
        self.QcbVersion.setText(QtWidgets.QApplication.translate("ExportWin", "与通过文件版本一致", None, -1))
        self.QcbNormals.setText(QtWidgets.QApplication.translate("ExportWin", "无法线", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("ExportWin", "文件格式：", None, -1))
        self.QcbUvSets.setText(QtWidgets.QApplication.translate("ExportWin", "写入 UV 集", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("ExportWin", "输出类型：", None, -1))
        self.QcbClothNcache.setText(QtWidgets.QApplication.translate("ExportWin", "布料解算形态缓存", None, -1))
        self.QcbCurveNcache.setText(QtWidgets.QApplication.translate("ExportWin", "毛发引导曲线缓存", None, -1))
        self.QrbExClassic.setText(QtWidgets.QApplication.translate("ExportWin", "当前视窗模式输出", None, -1))
        self.QrbExPrompt.setText(QtWidgets.QApplication.translate("ExportWin", "当前任务后台输出", None, -1))
        self.QrbExClient.setText(QtWidgets.QApplication.translate("ExportWin", "任务移交到客户端", None, -1))
        self.QrbHDF5.setText(QtWidgets.QApplication.translate("ExportWin", "HDF5 - Maya 2014 Ext 1 和旧版", None, -1))
        self.QrbOgawa.setText(QtWidgets.QApplication.translate("ExportWin", "Ogawa - Maya 2014 Ext 1", None, -1))
        self.tabWidgetEdit.setTabText(self.tabWidgetEdit.indexOf(self.tabExport), QtWidgets.QApplication.translate("ExportWin", "导出", None, -1))
        self.tabWidgetEdit.setTabText(self.tabWidgetEdit.indexOf(self.tabNote), QtWidgets.QApplication.translate("ExportWin", "备注", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("ExportWin", "动画", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("ExportWin", "毛发", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("ExportWin", "布料", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("ExportWin", "毛布", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("ExportWin", "未加载", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("ExportWin", "TextLabel", None, -1))

