# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'publishWindow.ui'
#
# Created: Tue May 31 21:25:26 2022
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1054, 698)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.QpbRefresh = QtWidgets.QPushButton(self.frame)
        self.QpbRefresh.setMinimumSize(QtCore.QSize(75, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbRefresh.setFont(font)
        self.QpbRefresh.setObjectName("QpbRefresh")
        self.horizontalLayout.addWidget(self.QpbRefresh)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameBusiness = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameBusiness.sizePolicy().hasHeightForWidth())
        self.frameBusiness.setSizePolicy(sizePolicy)
        self.frameBusiness.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBusiness.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameBusiness.setLineWidth(0)
        self.frameBusiness.setObjectName("frameBusiness")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameBusiness)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.QcbProject = QtWidgets.QComboBox(self.frameBusiness)
        self.QcbProject.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbProject.setFont(font)
        self.QcbProject.setObjectName("QcbProject")
        self.verticalLayout_2.addWidget(self.QcbProject)
        self.frameBusiness2Shots = QtWidgets.QFrame(self.frameBusiness)
        self.frameBusiness2Shots.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBusiness2Shots.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBusiness2Shots.setObjectName("frameBusiness2Shots")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frameBusiness2Shots)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.QcbExtend1 = QtWidgets.QComboBox(self.frameBusiness2Shots)
        self.QcbExtend1.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbExtend1.setFont(font)
        self.QcbExtend1.setObjectName("QcbExtend1")
        self.horizontalLayout_3.addWidget(self.QcbExtend1)
        self.QcbExtend2 = QtWidgets.QComboBox(self.frameBusiness2Shots)
        self.QcbExtend2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbExtend2.setFont(font)
        self.QcbExtend2.setObjectName("QcbExtend2")
        self.horizontalLayout_3.addWidget(self.QcbExtend2)
        self.verticalLayout_2.addWidget(self.frameBusiness2Shots)
        self.QcbCategory = QtWidgets.QComboBox(self.frameBusiness)
        self.QcbCategory.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbCategory.setFont(font)
        self.QcbCategory.setObjectName("QcbCategory")
        self.verticalLayout_2.addWidget(self.QcbCategory)
        self.QlwTask = QtWidgets.QListWidget(self.frameBusiness)
        self.QlwTask.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwTask.setFont(font)
        self.QlwTask.setObjectName("QlwTask")
        self.verticalLayout_2.addWidget(self.QlwTask)
        self.QcbBusiness = QtWidgets.QComboBox(self.frameBusiness)
        self.QcbBusiness.setMinimumSize(QtCore.QSize(0, 0))
        self.QcbBusiness.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbBusiness.setFont(font)
        self.QcbBusiness.setObjectName("QcbBusiness")
        self.verticalLayout_2.addWidget(self.QcbBusiness)
        self.horizontalLayout_2.addWidget(self.frameBusiness)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tabUpstream = QtWidgets.QWidget()
        self.tabUpstream.setObjectName("tabUpstream")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabUpstream)
        self.gridLayout_5.setSpacing(5)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.QlwUpstream = QtWidgets.QListWidget(self.tabUpstream)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwUpstream.setFont(font)
        self.QlwUpstream.setObjectName("QlwUpstream")
        self.gridLayout_5.addWidget(self.QlwUpstream, 0, 0, 1, 1)
        self.QpbUpstream = QtWidgets.QPushButton(self.tabUpstream)
        self.QpbUpstream.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbUpstream.setFont(font)
        self.QpbUpstream.setObjectName("QpbUpstream")
        self.gridLayout_5.addWidget(self.QpbUpstream, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabUpstream, "")
        self.tabArchive = QtWidgets.QWidget()
        self.tabArchive.setObjectName("tabArchive")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabArchive)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.QpbOpen = QtWidgets.QPushButton(self.tabArchive)
        self.QpbOpen.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbOpen.setFont(font)
        self.QpbOpen.setObjectName("QpbOpen")
        self.gridLayout_2.addWidget(self.QpbOpen, 1, 0, 1, 1)
        self.QpbSave = QtWidgets.QPushButton(self.tabArchive)
        self.QpbSave.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbSave.setFont(font)
        self.QpbSave.setObjectName("QpbSave")
        self.gridLayout_2.addWidget(self.QpbSave, 1, 1, 1, 1)
        self.QpbWork = QtWidgets.QPushButton(self.tabArchive)
        self.QpbWork.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbWork.setFont(font)
        self.QpbWork.setObjectName("QpbWork")
        self.gridLayout_2.addWidget(self.QpbWork, 1, 2, 1, 1)
        self.QlwArchive = QtWidgets.QListWidget(self.tabArchive)
        self.QlwArchive.setObjectName("QlwArchive")
        self.gridLayout_2.addWidget(self.QlwArchive, 0, 0, 1, 3)
        self.tabWidget.addTab(self.tabArchive, "")
        self.tabEnv = QtWidgets.QWidget()
        self.tabEnv.setObjectName("tabEnv")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabEnv)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.QlwEnv = QtWidgets.QListWidget(self.tabEnv)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlwEnv.setFont(font)
        self.QlwEnv.setDragEnabled(False)
        self.QlwEnv.setIconSize(QtCore.QSize(96, 96))
        self.QlwEnv.setResizeMode(QtWidgets.QListView.Adjust)
        self.QlwEnv.setSpacing(5)
        self.QlwEnv.setViewMode(QtWidgets.QListView.IconMode)
        self.QlwEnv.setObjectName("QlwEnv")
        self.verticalLayout_5.addWidget(self.QlwEnv)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.tabEnv)
        self.label_2.setMinimumSize(QtCore.QSize(44, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(65, 65, 65);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.tabEnv)
        self.label_4.setMinimumSize(QtCore.QSize(44, 0))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(112, 182, 3);\n"
"color: rgb(65, 65, 65);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.QleSearch = QtWidgets.QLineEdit(self.tabEnv)
        self.QleSearch.setMinimumSize(QtCore.QSize(0, 26))
        self.QleSearch.setMaximumSize(QtCore.QSize(128, 16777215))
        self.QleSearch.setObjectName("QleSearch")
        self.horizontalLayout_5.addWidget(self.QleSearch)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tabEnv, "")
        self.tabDailies = QtWidgets.QWidget()
        self.tabDailies.setObjectName("tabDailies")
        self.gridLayout = QtWidgets.QGridLayout(self.tabDailies)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.QlabelRenderOffscreen = QtWidgets.QLabel(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlabelRenderOffscreen.setFont(font)
        self.QlabelRenderOffscreen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QlabelRenderOffscreen.setObjectName("QlabelRenderOffscreen")
        self.gridLayout.addWidget(self.QlabelRenderOffscreen, 9, 0, 1, 1)
        self.line2 = QtWidgets.QFrame(self.tabDailies)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setLineWidth(2)
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.gridLayout.addWidget(self.line2, 11, 0, 1, 3)
        self.QlabelViewport = QtWidgets.QLabel(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlabelViewport.setFont(font)
        self.QlabelViewport.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QlabelViewport.setObjectName("QlabelViewport")
        self.gridLayout.addWidget(self.QlabelViewport, 10, 0, 1, 1)
        self.QlabelView = QtWidgets.QLabel(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlabelView.setFont(font)
        self.QlabelView.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QlabelView.setObjectName("QlabelView")
        self.gridLayout.addWidget(self.QlabelView, 7, 0, 1, 1)
        self.QlabelShowOrnaments = QtWidgets.QLabel(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlabelShowOrnaments.setFont(font)
        self.QlabelShowOrnaments.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QlabelShowOrnaments.setObjectName("QlabelShowOrnaments")
        self.gridLayout.addWidget(self.QlabelShowOrnaments, 8, 0, 1, 1)
        self.QpbDailies = QtWidgets.QPushButton(self.tabDailies)
        self.QpbDailies.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.QpbDailies.setFont(font)
        self.QpbDailies.setObjectName("QpbDailies")
        self.gridLayout.addWidget(self.QpbDailies, 29, 0, 1, 3)
        self.QsbEnd = QtWidgets.QSpinBox(self.tabDailies)
        self.QsbEnd.setEnabled(False)
        self.QsbEnd.setMaximum(10000)
        self.QsbEnd.setProperty("value", 124)
        self.QsbEnd.setObjectName("QsbEnd")
        self.gridLayout.addWidget(self.QsbEnd, 20, 2, 1, 1)
        self.QcbFormat = QtWidgets.QComboBox(self.tabDailies)
        self.QcbFormat.setObjectName("QcbFormat")
        self.gridLayout.addWidget(self.QcbFormat, 12, 1, 1, 1)
        self.QlabelStartEnd = QtWidgets.QLabel(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlabelStartEnd.setFont(font)
        self.QlabelStartEnd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QlabelStartEnd.setObjectName("QlabelStartEnd")
        self.gridLayout.addWidget(self.QlabelStartEnd, 20, 0, 1, 1)
        self.QsbQuality = QtWidgets.QSpinBox(self.tabDailies)
        self.QsbQuality.setMaximum(100)
        self.QsbQuality.setProperty("value", 75)
        self.QsbQuality.setObjectName("QsbQuality")
        self.gridLayout.addWidget(self.QsbQuality, 16, 1, 1, 1)
        self.QlabelFps = QtWidgets.QLabel(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlabelFps.setFont(font)
        self.QlabelFps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QlabelFps.setObjectName("QlabelFps")
        self.gridLayout.addWidget(self.QlabelFps, 19, 0, 1, 1)
        self.QlabelQuality = QtWidgets.QLabel(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlabelQuality.setFont(font)
        self.QlabelQuality.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QlabelQuality.setObjectName("QlabelQuality")
        self.gridLayout.addWidget(self.QlabelQuality, 16, 0, 1, 1)
        self.QcbMulti = QtWidgets.QCheckBox(self.tabDailies)
        self.QcbMulti.setText("")
        self.QcbMulti.setChecked(False)
        self.QcbMulti.setObjectName("QcbMulti")
        self.gridLayout.addWidget(self.QcbMulti, 10, 1, 1, 2)
        self.QcbOffscreen = QtWidgets.QCheckBox(self.tabDailies)
        self.QcbOffscreen.setText("")
        self.QcbOffscreen.setChecked(True)
        self.QcbOffscreen.setObjectName("QcbOffscreen")
        self.gridLayout.addWidget(self.QcbOffscreen, 9, 1, 1, 2)
        self.line1 = QtWidgets.QFrame(self.tabDailies)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setLineWidth(2)
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.gridLayout.addWidget(self.line1, 17, 0, 1, 3)
        self.QsbWidth = QtWidgets.QSpinBox(self.tabDailies)
        self.QsbWidth.setEnabled(False)
        self.QsbWidth.setMaximum(10000)
        self.QsbWidth.setProperty("value", 1280)
        self.QsbWidth.setObjectName("QsbWidth")
        self.gridLayout.addWidget(self.QsbWidth, 18, 1, 1, 1)
        self.QlabelEncoding = QtWidgets.QLabel(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlabelEncoding.setFont(font)
        self.QlabelEncoding.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QlabelEncoding.setObjectName("QlabelEncoding")
        self.gridLayout.addWidget(self.QlabelEncoding, 13, 0, 1, 1)
        self.QsliderScale = QtWidgets.QSlider(self.tabDailies)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QsliderScale.sizePolicy().hasHeightForWidth())
        self.QsliderScale.setSizePolicy(sizePolicy)
        self.QsliderScale.setMaximum(100)
        self.QsliderScale.setProperty("value", 100)
        self.QsliderScale.setOrientation(QtCore.Qt.Horizontal)
        self.QsliderScale.setObjectName("QsliderScale")
        self.gridLayout.addWidget(self.QsliderScale, 21, 2, 1, 1)
        self.QlabelFormat = QtWidgets.QLabel(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlabelFormat.setFont(font)
        self.QlabelFormat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QlabelFormat.setObjectName("QlabelFormat")
        self.gridLayout.addWidget(self.QlabelFormat, 12, 0, 1, 1)
        self.QcbView = QtWidgets.QCheckBox(self.tabDailies)
        self.QcbView.setText("")
        self.QcbView.setChecked(True)
        self.QcbView.setObjectName("QcbView")
        self.gridLayout.addWidget(self.QcbView, 7, 1, 1, 2)
        self.QsbScale = QtWidgets.QSpinBox(self.tabDailies)
        self.QsbScale.setMaximum(100)
        self.QsbScale.setProperty("value", 100)
        self.QsbScale.setObjectName("QsbScale")
        self.gridLayout.addWidget(self.QsbScale, 21, 1, 1, 1)
        self.line3 = QtWidgets.QFrame(self.tabDailies)
        self.line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line3.setLineWidth(2)
        self.line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line3.setObjectName("line3")
        self.gridLayout.addWidget(self.line3, 22, 0, 1, 3)
        self.QlabelScale = QtWidgets.QLabel(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlabelScale.setFont(font)
        self.QlabelScale.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QlabelScale.setObjectName("QlabelScale")
        self.gridLayout.addWidget(self.QlabelScale, 21, 0, 1, 1)
        self.QlabelDisplaySize = QtWidgets.QLabel(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlabelDisplaySize.setFont(font)
        self.QlabelDisplaySize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QlabelDisplaySize.setObjectName("QlabelDisplaySize")
        self.gridLayout.addWidget(self.QlabelDisplaySize, 14, 0, 1, 1)
        self.QlabelResolution = QtWidgets.QLabel(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlabelResolution.setFont(font)
        self.QlabelResolution.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QlabelResolution.setObjectName("QlabelResolution")
        self.gridLayout.addWidget(self.QlabelResolution, 18, 0, 1, 1)
        self.QsliderQuality = QtWidgets.QSlider(self.tabDailies)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QsliderQuality.sizePolicy().hasHeightForWidth())
        self.QsliderQuality.setSizePolicy(sizePolicy)
        self.QsliderQuality.setMaximum(100)
        self.QsliderQuality.setProperty("value", 75)
        self.QsliderQuality.setOrientation(QtCore.Qt.Horizontal)
        self.QsliderQuality.setObjectName("QsliderQuality")
        self.gridLayout.addWidget(self.QsliderQuality, 16, 2, 1, 1)
        self.QsbHeight = QtWidgets.QSpinBox(self.tabDailies)
        self.QsbHeight.setEnabled(False)
        self.QsbHeight.setMaximum(10000)
        self.QsbHeight.setProperty("value", 720)
        self.QsbHeight.setObjectName("QsbHeight")
        self.gridLayout.addWidget(self.QsbHeight, 18, 2, 1, 1)
        self.QsbStart = QtWidgets.QSpinBox(self.tabDailies)
        self.QsbStart.setEnabled(False)
        self.QsbStart.setMaximum(10000)
        self.QsbStart.setProperty("value", 101)
        self.QsbStart.setObjectName("QsbStart")
        self.gridLayout.addWidget(self.QsbStart, 20, 1, 1, 1)
        self.QcbOrnaments = QtWidgets.QCheckBox(self.tabDailies)
        self.QcbOrnaments.setText("")
        self.QcbOrnaments.setChecked(True)
        self.QcbOrnaments.setObjectName("QcbOrnaments")
        self.gridLayout.addWidget(self.QcbOrnaments, 8, 1, 1, 2)
        self.QcbEncoding = QtWidgets.QComboBox(self.tabDailies)
        self.QcbEncoding.setObjectName("QcbEncoding")
        self.gridLayout.addWidget(self.QcbEncoding, 13, 1, 1, 1)
        self.QcbSize = QtWidgets.QComboBox(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbSize.setFont(font)
        self.QcbSize.setObjectName("QcbSize")
        self.QcbSize.addItem("")
        self.gridLayout.addWidget(self.QcbSize, 14, 1, 1, 1)
        self.QcbPlaybackSpeed = QtWidgets.QComboBox(self.tabDailies)
        self.QcbPlaybackSpeed.setEnabled(False)
        self.QcbPlaybackSpeed.setObjectName("QcbPlaybackSpeed")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.QcbPlaybackSpeed.addItem("")
        self.gridLayout.addWidget(self.QcbPlaybackSpeed, 19, 1, 1, 1)
        self.vlCustom = QtWidgets.QVBoxLayout()
        self.vlCustom.setSpacing(0)
        self.vlCustom.setContentsMargins(-1, -1, -1, 0)
        self.vlCustom.setObjectName("vlCustom")
        self.QcbDisplayShade = QtWidgets.QCheckBox(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbDisplayShade.setFont(font)
        self.QcbDisplayShade.setChecked(True)
        self.QcbDisplayShade.setObjectName("QcbDisplayShade")
        self.vlCustom.addWidget(self.QcbDisplayShade)
        self.QcbDisplayWireframe = QtWidgets.QCheckBox(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbDisplayWireframe.setFont(font)
        self.QcbDisplayWireframe.setObjectName("QcbDisplayWireframe")
        self.vlCustom.addWidget(self.QcbDisplayWireframe)
        self.QcbDisplayCurves = QtWidgets.QCheckBox(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbDisplayCurves.setFont(font)
        self.QcbDisplayCurves.setObjectName("QcbDisplayCurves")
        self.vlCustom.addWidget(self.QcbDisplayCurves)
        self.QcbDisplayGrid = QtWidgets.QCheckBox(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbDisplayGrid.setFont(font)
        self.QcbDisplayGrid.setObjectName("QcbDisplayGrid")
        self.vlCustom.addWidget(self.QcbDisplayGrid)
        self.gridLayout.addLayout(self.vlCustom, 23, 1, 1, 2)
        self.QlabelView_2 = QtWidgets.QLabel(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QlabelView_2.setFont(font)
        self.QlabelView_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.QlabelView_2.setObjectName("QlabelView_2")
        self.gridLayout.addWidget(self.QlabelView_2, 0, 0, 1, 1)
        self.vlRender = QtWidgets.QVBoxLayout()
        self.vlRender.setSpacing(0)
        self.vlRender.setContentsMargins(-1, -1, -1, 0)
        self.vlRender.setObjectName("vlRender")
        self.QcbDisplayViewport20 = QtWidgets.QCheckBox(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbDisplayViewport20.setFont(font)
        self.QcbDisplayViewport20.setChecked(True)
        self.QcbDisplayViewport20.setObjectName("QcbDisplayViewport20")
        self.vlRender.addWidget(self.QcbDisplayViewport20)
        self.QcbOcclusion = QtWidgets.QCheckBox(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbOcclusion.setFont(font)
        self.QcbOcclusion.setChecked(True)
        self.QcbOcclusion.setObjectName("QcbOcclusion")
        self.vlRender.addWidget(self.QcbOcclusion)
        self.QcbBlur = QtWidgets.QCheckBox(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbBlur.setFont(font)
        self.QcbBlur.setObjectName("QcbBlur")
        self.vlRender.addWidget(self.QcbBlur)
        self.line_2 = QtWidgets.QFrame(self.tabDailies)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.vlRender.addWidget(self.line_2)
        self.QcbDisplayHUD = QtWidgets.QCheckBox(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbDisplayHUD.setFont(font)
        self.QcbDisplayHUD.setChecked(True)
        self.QcbDisplayHUD.setObjectName("QcbDisplayHUD")
        self.vlRender.addWidget(self.QcbDisplayHUD)
        self.QcbSafeAction = QtWidgets.QCheckBox(self.tabDailies)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QcbSafeAction.setFont(font)
        self.QcbSafeAction.setChecked(True)
        self.QcbSafeAction.setObjectName("QcbSafeAction")
        self.vlRender.addWidget(self.QcbSafeAction)
        self.gridLayout.addLayout(self.vlRender, 0, 1, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 24, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.tabDailies)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 6, 0, 1, 3)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.tabWidget.addTab(self.tabDailies, "")
        self.tabSubmit = QtWidgets.QWidget()
        self.tabSubmit.setObjectName("tabSubmit")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabSubmit)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.tabSubmit)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 876, 527))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.collectorsLayout = QtWidgets.QVBoxLayout()
        self.collectorsLayout.setSpacing(5)
        self.collectorsLayout.setContentsMargins(-1, -1, -1, 0)
        self.collectorsLayout.setObjectName("collectorsLayout")
        self.verticalLayout_3.addLayout(self.collectorsLayout)
        self.checklistLayout = QtWidgets.QVBoxLayout()
        self.checklistLayout.setSpacing(5)
        self.checklistLayout.setObjectName("checklistLayout")
        self.verticalLayout_3.addLayout(self.checklistLayout)
        self.validatorsLayout = QtWidgets.QVBoxLayout()
        self.validatorsLayout.setSpacing(5)
        self.validatorsLayout.setObjectName("validatorsLayout")
        self.verticalLayout_3.addLayout(self.validatorsLayout)
        self.extractorsLayout = QtWidgets.QVBoxLayout()
        self.extractorsLayout.setSpacing(5)
        self.extractorsLayout.setObjectName("extractorsLayout")
        self.verticalLayout_3.addLayout(self.extractorsLayout)
        self.integratorsLayout = QtWidgets.QVBoxLayout()
        self.integratorsLayout.setSpacing(5)
        self.integratorsLayout.setObjectName("integratorsLayout")
        self.verticalLayout_3.addLayout(self.integratorsLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.hlExtend = QtWidgets.QHBoxLayout()
        self.hlExtend.setSpacing(5)
        self.hlExtend.setContentsMargins(-1, -1, -1, 0)
        self.hlExtend.setObjectName("hlExtend")
        self.QpbAvatar = QtWidgets.QPushButton(self.tabSubmit)
        self.QpbAvatar.setMaximumSize(QtCore.QSize(24, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QpbAvatar.setFont(font)
        self.QpbAvatar.setObjectName("QpbAvatar")
        self.hlExtend.addWidget(self.QpbAvatar)
        self.gbSubmit = QtWidgets.QGroupBox(self.tabSubmit)
        self.gbSubmit.setMinimumSize(QtCore.QSize(0, 0))
        self.gbSubmit.setMaximumSize(QtCore.QSize(168, 28))
        self.gbSubmit.setStyleSheet("")
        self.gbSubmit.setTitle("")
        self.gbSubmit.setObjectName("gbSubmit")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.gbSubmit)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.QrbDailies = QtWidgets.QRadioButton(self.gbSubmit)
        self.QrbDailies.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbDailies.setFont(font)
        self.QrbDailies.setObjectName("QrbDailies")
        self.horizontalLayout_6.addWidget(self.QrbDailies)
        self.QrbPublish = QtWidgets.QRadioButton(self.gbSubmit)
        self.QrbPublish.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QrbPublish.setFont(font)
        self.QrbPublish.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.QrbPublish.setObjectName("QrbPublish")
        self.horizontalLayout_6.addWidget(self.QrbPublish)
        self.hlExtend.addWidget(self.gbSubmit)
        self.QpbSubmit = QtWidgets.QPushButton(self.tabSubmit)
        self.QpbSubmit.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.QpbSubmit.setFont(font)
        self.QpbSubmit.setObjectName("QpbSubmit")
        self.hlExtend.addWidget(self.QpbSubmit)
        self.verticalLayout_4.addLayout(self.hlExtend)
        self.tabWidget.addTab(self.tabSubmit, "")
        self.tabNotes = QtWidgets.QWidget()
        self.tabNotes.setObjectName("tabNotes")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabNotes)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setHorizontalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.QteNotes = QtWidgets.QTextEdit(self.tabNotes)
        self.QteNotes.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QteNotes.setFont(font)
        self.QteNotes.setStyleSheet("color: rgb(125, 125, 125);")
        self.QteNotes.setObjectName("QteNotes")
        self.gridLayout_3.addWidget(self.QteNotes, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabNotes, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.version = QtWidgets.QLabel(Form)
        self.version.setMinimumSize(QtCore.QSize(0, 24))
        self.version.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.version.setFont(font)
        self.version.setStyleSheet("color: rgb(150, 150, 150);")
        self.version.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.version.setObjectName("version")
        self.horizontalLayout_4.addWidget(self.version)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.progressBar.setFont(font)
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        self.QcbPlaybackSpeed.setCurrentIndex(12)
        QtCore.QObject.connect(self.QsliderQuality, QtCore.SIGNAL("valueChanged(int)"), self.QsbQuality.setValue)
        QtCore.QObject.connect(self.QsbQuality, QtCore.SIGNAL("valueChanged(int)"), self.QsliderQuality.setValue)
        QtCore.QObject.connect(self.QsliderScale, QtCore.SIGNAL("valueChanged(int)"), self.QsbScale.setValue)
        QtCore.QObject.connect(self.QsbScale, QtCore.SIGNAL("valueChanged(int)"), self.QsliderScale.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.QpbRefresh.setText(QtWidgets.QApplication.translate("Form", "刷新界面", None, -1))
        self.QpbUpstream.setText(QtWidgets.QApplication.translate("Form", "导入", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUpstream), QtWidgets.QApplication.translate("Form", "上游", None, -1))
        self.QpbOpen.setText(QtWidgets.QApplication.translate("Form", "打开文件", None, -1))
        self.QpbSave.setText(QtWidgets.QApplication.translate("Form", "保存当前", None, -1))
        self.QpbWork.setText(QtWidgets.QApplication.translate("Form", "工程新版", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabArchive), QtWidgets.QApplication.translate("Form", "存档", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "空的", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "完成", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEnv), QtWidgets.QApplication.translate("Form", "环境", None, -1))
        self.QlabelRenderOffscreen.setText(QtWidgets.QApplication.translate("Form", "离屏渲染:", None, -1))
        self.QlabelViewport.setText(QtWidgets.QApplication.translate("Form", "多摄影机输出:", None, -1))
        self.QlabelView.setText(QtWidgets.QApplication.translate("Form", "视图:", None, -1))
        self.QlabelShowOrnaments.setText(QtWidgets.QApplication.translate("Form", "显示装饰:", None, -1))
        self.QpbDailies.setText(QtWidgets.QApplication.translate("Form", "拍屏", None, -1))
        self.QlabelStartEnd.setText(QtWidgets.QApplication.translate("Form", "起始帧/结束帧:", None, -1))
        self.QlabelFps.setText(QtWidgets.QApplication.translate("Form", "播放速度:", None, -1))
        self.QlabelQuality.setText(QtWidgets.QApplication.translate("Form", "质量:", None, -1))
        self.QlabelEncoding.setText(QtWidgets.QApplication.translate("Form", "编码:", None, -1))
        self.QlabelFormat.setText(QtWidgets.QApplication.translate("Form", "格式:", None, -1))
        self.QlabelScale.setText(QtWidgets.QApplication.translate("Form", "缩放:", None, -1))
        self.QlabelDisplaySize.setText(QtWidgets.QApplication.translate("Form", "显示大小:", None, -1))
        self.QlabelResolution.setText(QtWidgets.QApplication.translate("Form", "图像大小:", None, -1))
        self.QcbSize.setItemText(0, QtWidgets.QApplication.translate("Form", "来自渲染设置", None, -1))
        self.QcbPlaybackSpeed.setItemText(0, QtWidgets.QApplication.translate("Form", "2fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(1, QtWidgets.QApplication.translate("Form", "3fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(2, QtWidgets.QApplication.translate("Form", "4fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(3, QtWidgets.QApplication.translate("Form", "5fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(4, QtWidgets.QApplication.translate("Form", "6fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(5, QtWidgets.QApplication.translate("Form", "8fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(6, QtWidgets.QApplication.translate("Form", "10fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(7, QtWidgets.QApplication.translate("Form", "12fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(8, QtWidgets.QApplication.translate("Form", "15fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(9, QtWidgets.QApplication.translate("Form", "16fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(10, QtWidgets.QApplication.translate("Form", "20fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(11, QtWidgets.QApplication.translate("Form", "23.976fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(12, QtWidgets.QApplication.translate("Form", "24fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(13, QtWidgets.QApplication.translate("Form", "25fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(14, QtWidgets.QApplication.translate("Form", "29.97fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(15, QtWidgets.QApplication.translate("Form", "29.97df", None, -1))
        self.QcbPlaybackSpeed.setItemText(16, QtWidgets.QApplication.translate("Form", "30fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(17, QtWidgets.QApplication.translate("Form", "40fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(18, QtWidgets.QApplication.translate("Form", "47.952fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(19, QtWidgets.QApplication.translate("Form", "48fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(20, QtWidgets.QApplication.translate("Form", "50fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(21, QtWidgets.QApplication.translate("Form", "59.94fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(22, QtWidgets.QApplication.translate("Form", "60fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(23, QtWidgets.QApplication.translate("Form", "75fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(24, QtWidgets.QApplication.translate("Form", "80fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(25, QtWidgets.QApplication.translate("Form", "100fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(26, QtWidgets.QApplication.translate("Form", "120fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(27, QtWidgets.QApplication.translate("Form", "125fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(28, QtWidgets.QApplication.translate("Form", "150fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(29, QtWidgets.QApplication.translate("Form", "200fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(30, QtWidgets.QApplication.translate("Form", "240fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(31, QtWidgets.QApplication.translate("Form", "250fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(32, QtWidgets.QApplication.translate("Form", "300fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(33, QtWidgets.QApplication.translate("Form", "375fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(34, QtWidgets.QApplication.translate("Form", "400fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(35, QtWidgets.QApplication.translate("Form", "500fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(36, QtWidgets.QApplication.translate("Form", "600fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(37, QtWidgets.QApplication.translate("Form", "750fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(38, QtWidgets.QApplication.translate("Form", "1200fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(39, QtWidgets.QApplication.translate("Form", "1500fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(40, QtWidgets.QApplication.translate("Form", "2000fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(41, QtWidgets.QApplication.translate("Form", "3000fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(42, QtWidgets.QApplication.translate("Form", "6000fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(43, QtWidgets.QApplication.translate("Form", "44100fps", None, -1))
        self.QcbPlaybackSpeed.setItemText(44, QtWidgets.QApplication.translate("Form", "48000fps", None, -1))
        self.QcbDisplayShade.setText(QtWidgets.QApplication.translate("Form", "对所有项目进行平滑着色处理", None, -1))
        self.QcbDisplayWireframe.setText(QtWidgets.QApplication.translate("Form", "作色对象上的线框", None, -1))
        self.QcbDisplayCurves.setText(QtWidgets.QApplication.translate("Form", "NURBS 曲线", None, -1))
        self.QcbDisplayGrid.setText(QtWidgets.QApplication.translate("Form", "栅格", None, -1))
        self.QlabelView_2.setText(QtWidgets.QApplication.translate("Form", "渲染器:", None, -1))
        self.QcbDisplayViewport20.setText(QtWidgets.QApplication.translate("Form", "Viewport 2.0", None, -1))
        self.QcbOcclusion.setText(QtWidgets.QApplication.translate("Form", "屏幕空间环境光遮挡", None, -1))
        self.QcbBlur.setText(QtWidgets.QApplication.translate("Form", "运动模糊", None, -1))
        self.QcbDisplayHUD.setText(QtWidgets.QApplication.translate("Form", "平视显示仪", None, -1))
        self.QcbSafeAction.setText(QtWidgets.QApplication.translate("Form", "安全动作", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDailies), QtWidgets.QApplication.translate("Form", "日报", None, -1))
        self.QpbAvatar.setText(QtWidgets.QApplication.translate("Form", "+", None, -1))
        self.QrbDailies.setText(QtWidgets.QApplication.translate("Form", "效果", None, -1))
        self.QrbPublish.setText(QtWidgets.QApplication.translate("Form", "工程", None, -1))
        self.QpbSubmit.setText(QtWidgets.QApplication.translate("Form", "验证", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSubmit), QtWidgets.QApplication.translate("Form", "提交", None, -1))
        self.QteNotes.setHtml(QtWidgets.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">文档：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">(1)单击任务时触发文档列表框</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">(2)在列表框内选择条目后完成允许打开文件</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNotes), QtWidgets.QApplication.translate("Form", "注释", None, -1))
        self.version.setText(QtWidgets.QApplication.translate("Form", "版本", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "提示", None, -1))

